### ISSUE TITLE
Failed to run '/snap/bin/go env' error with version 0.24.0

### ISSUE THREAD

**Issue by chrisesimpson** [golang/vscode-go#1411]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.2 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.9
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.55.1
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.24.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.

```
    Checking configured tools....
    GOBIN: undefined
    toolsGopath: 
    gopath: /home/chris/go
    GOROOT: 
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/chris/go/bin:/usr/local/go/bin:/home/chris/go/bin

    cached Go version ({"binaryPath":"/snap/bin/go","version":""}) is invalid, recomputing
    unable to determine version from the output of "/snap/bin/go version": "undefined"
    gopkgs: /home/chris/go/bin/gopkgs installed
    go-outline: /home/chris/go/bin/go-outline installed
    gotests: /home/chris/go/bin/gotests installed
    gomodifytags: /home/chris/go/bin/gomodifytags installed
    impl: /home/chris/go/bin/impl installed
    goplay: /home/chris/go/bin/goplay installed
    dlv: /home/chris/go/bin/dlv installed
    dlv-dap: dlv-dap not installed
    staticcheck: /home/chris/go/bin/staticcheck installed
    gopls: /home/chris/go/bin/gopls installed

    go env
    Workspace Folder (redo-engine-go-poc2): /home/chris/dev/redo-engine/redo-engine-go-poc2	

```
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "go.toolsManagement.autoUpdate": true,

### Describe the bug
A clear and concise description of what the bug.

When I start VS Code, I get the the following in my notifications:

    Failed to run '/snap/bin/go env. The config change may not be applied correctly.

And this in my output:

    Failed to run '/snap/bin/go env' (cwd: /home/chris/dev/redo-engine/redo-engine-go-poc2): Error: Command failed: /snap/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE

And I don't get any of the go dev tools features I expect (including "Go to Definition", "Find all References", etc)

If I run the command it says is failing from a vscode terminal window, I get the following:

```
$ /snap/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
{
        "GOBIN": "",
        "GOMODCACHE": "/home/chris/go/pkg/mod",
        "GOPATH": "/home/chris/go",
        "GOPROXY": "https://proxy.golang.org,direct",
        "GOROOT": "/snap/go/7221"
}
```

I expect it to work as it did with the previous version. If I downgrade to version 0.23.3 I can right click code and  the menu items are there "Go to Definition", "Find all References", etc

### Steps to reproduce the behavior:
1. Upgrade to version 0.24.0
2. Get errors describe above and lose dev tools functionality
